### PR TITLE
makefiles for building rest-server and auth-server

### PR DESCRIPTION
**Pull request by dennybaa**
- automatic sbt script installation into harness_root/sbt/sbt
  use of community sbtx (https://github.com/paulp/sbt-extras), **moving sbt/sbt out of the project tree**.
- "standard" makefiles instead of `make-distribution-*.sh`

# rest-server

```shell
# build
cd rest-server
make
```

```shell
# dist (only dist directory is populated no archive!!!)
cd rest-server
make dist
```
# auth-server

```shell
# build
cd rest-server/auth-server
make

# >> check rest-server/dist
```

```shell
# dist (only dist directory is populated no archive!!!)
cd rest-server/auth-server
make dist

# >> check rest-server/auth-server/dist
```

### CODE REVIEW

**Review by qqmbr4k — APPROVED** [review]

**Comment by pferrel** [comment]
@dennybaa I didn't expect you to take this as far as you did. 

We are working off a refactored repo structure in `release/0.3.0-RC1` where the auth-server and the java sdk are in new repos split from Harness. The reason is that they have not changed in a year or more.

See the master branch of:
https://github.com/actionml/harness-java-sdk
https://github.com/actionml/harness-auth-server

in the `release/0.3.0-RC1` branch there is no longer a `harness/auth-server` or `harness/java-sdk`

Since the python sdk is tightly connected to the Harness REST API (supports much more of the API than the Java SDK) it is kept with Harness for now.

I would retarget this to the release branch to see diffs and see if it does what you want.

**Comment by dennybaa** [comment]
> @dennybaa (https://link.getmailspring.com/link/1537388643.local-62203720-8bbe-v1.4.2-f587b7b7@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fdennybaa&recipient=cmVwbHkrMDAwZDlhMWIyMGJkNWJjMTk1MjgwYmUyZmU4ZDkzYTNiMWNiY2RkZTgyZTg2ODEyOTJjZjAwMDAwMDAxMTdiYTVhMDA5MmExNjljZTE1N2Y4NTBmQHJlcGx5LmdpdGh1Yi5jb20%3D) I didn't expect you to take this as far as you did.
>
> We are working off a refactored repo structure in release/0.3.0-RC1 where the auth-server and the java sdk are in new repos split from Harness. The reason is that they have not changed in a year or more.

Oh I see now. I was kept unaware. It would be nice if you could update me. Anyways this will be trivial to move.
>
> See the master branch of:
> https://github.com/actionml/harness-java-sdk (https://link.getmailspring.com/link/1537388643.local-62203720-8bbe-v1.4.2-f587b7b7@getmailspring.com/1?redirect=https%3A%2F%2Fgithub.com%2Factionml%2Fharness-java-sdk&recipient=cmVwbHkrMDAwZDlhMWIyMGJkNWJjMTk1MjgwYmUyZmU4ZDkzYTNiMWNiY2RkZTgyZTg2ODEyOTJjZjAwMDAwMDAxMTdiYTVhMDA5MmExNjljZTE1N2Y4NTBmQHJlcGx5LmdpdGh1Yi5jb20%3D)
> https://github.com/actionml/harness-auth-server (https://link.getmailspring.com/link/1537388643.local-62203720-8bbe-v1.4.2-f587b7b7@getmailspring.com/2?redirect=https%3A%2F%2Fgithub.com%2Factionml%2Fharness-auth-server&recipient=cmVwbHkrMDAwZDlhMWIyMGJkNWJjMTk1MjgwYmUyZmU4ZDkzYTNiMWNiY2RkZTgyZTg2ODEyOTJjZjAwMDAwMDAxMTdiYTVhMDA5MmExNjljZTE1N2Y4NTBmQHJlcGx5LmdpdGh1Yi5jb20%3D)
>
>
> in the release/0.3.0-RC1 branch there is no longer a harness/auth-server or harness/java-sdk`
>

Yup, exactly, I should've asked or you probably should've told me which are desired branches.
So let's schedule a syncup please...

**Comment by pferrel** [comment]
@dennybaa can you retarget this for `release/0.4.0-snapshot`? We'll use make to integrate new buildy, testy, packagy, things in one place. 

BTW that branch will be the starting point for the next release.

**Note** that now the Java SDK, and Auth Server are in separate repos.

**Comment by pferrel** [comment]
I merged this by hand to release/0.4.0-snapshot

@dennybaa will add your comments to a new markdown doc in the repo

**Pull request closed without merging**
